disabled_rules:
  - blanket_disable_command
  - nesting
  - implicit_getter
  - opening_brace
  - duplicate_conditions

excluded:
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
